apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubedata-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/zncdatadev/kubedata-catalog:latest
  displayName: Kubernetes Data Stack Operators
  publisher: ZNCDataDev Community
  updateStrategy:
    registryPoll:
      interval: 20m
